"""empty message

Revision ID: 231171e0fe50
Revises: 
Create Date: 2017-10-28 04:02:29.182812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231171e0fe50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotancy_request',
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.String(length=60), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotancy_request')
    # ### end Alembic commands ###
