"""empty message

Revision ID: fc3195cecb98
Revises: 231171e0fe50
Create Date: 2017-11-06 17:51:58.015959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3195cecb98'
down_revision = '231171e0fe50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_register_intention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('registration_data', sa.JSON(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('already_purchased', 'domain_register_intention', ['domain', 'finished'], unique=True, postgresql_where=sa.text('finished = true'))
    op.create_table('domain_registrant_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('account_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'provider', name='uix_1')
    )
    op.create_table('domain_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intention_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('provider_purchase_uid', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.Column('post_registration_complete', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['domain_registrant_account.id'], ),
    sa.ForeignKeyConstraint(['intention_id'], ['domain_register_intention.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intention_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_purchase')
    op.drop_table('domain_registrant_account')
    op.drop_index('already_purchased', table_name='domain_register_intention')
    op.drop_table('domain_register_intention')
    # ### end Alembic commands ###
